---
output: html_document
editor_options: 
  chunk_output_type: inline
---
---
title: "Lasma"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

Packages

```{r}
pacman::p_load(tidyverse, 
               janitor, 
               visdat, 
               gtsummary)
```

# Dataset
```{r}
df <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vTaTrujjc9aB_Q_eaGMewz20aH754r055zJ6rNb-sGy8gmehP1KkghtAiZ2DjycztaO1V7xOCdkpNAY/pub?gid=0&single=true&output=csv", 
               na = c("na"))
```


```{r}
head(df)
```
```{r}
df <- df %>% 
  janitor::clean_names()
```


Create a new ID column

```{r}
df <- df %>% 
  rowid_to_column("id")
```




Reformat the dataset

```{r}
df_long <- df %>% 
  pivot_longer(fb:dont_use, 
               names_to = "social_media", 
               values_to = "answer")
```


# DATA EXPLORATION

```{r}
df %>% 
  drop_na() %>% 
  # group_by(id) %>%
      mutate(age = 2020 - year) %>%
  select(power_position, 
         gender, age, 
         fb:dont_use) %>% 
  gtsummary::tbl_summary(by = power_position) %>% 
  gtsummary::add_p()
```

```{r}
df_long %>% 
  drop_na() %>% 
    ggplot(aes(x = social_media, 
             fill = answer)) + 
  geom_bar(position="fill") + 
  facet_grid(power_position~.) +
  theme_minimal() +
  labs(
    title = "Use of social media by power position", 
    x = "Social media", 
    y = "Percentage", 
    fill = "Answer"
  ) +
    scale_y_continuous(labels = scales::percent)
```



# Perceptions about tv

So, there are some questions about what they think about russian and latvian television

```{r}
df %>% 
  drop_na() %>% 
  # select only relevant columns
  select(respondent_id:parties, 
         lv_unbiased:ru_trustworhy) %>%
  # convert from wide to long
  pivot_longer(lv_unbiased:ru_trustworhy, 
               names_to = "question", 
               values_to = "answer") %>%
  # split the question in two columns
  separate(question, 
           into = c("LV_or_RU", "question")) %>% 
  # fix some wrong values
  mutate(question = recode(question, "know" = "know their subject", "trustworthy" = " media are trustworthy", "trustworhy" = " media are trustworthy", "comp" = "display complete picture", "complete" = "display complete picture", "unbiased" = "are unbiased", "truthful" = "report truthfully")) %>% 
  # change the format of the asnwer
  mutate(answer = as.factor(answer)) %>% 
  ggplot(aes(x = question, 
             fill = answer)) + 
    geom_bar(position = "fill") +
       scale_y_continuous(labels = scales::percent) +
    coord_flip() +
  facet_grid(.~LV_or_RU) + 
    # scale_fill_brewer(palette="Set4")
  scale_fill_manual(name = "Answers", labels = c("Absolutely disagree", "Disagree", "Neither agree nor disagree", "Agree", "Absolutely agree"), values = c("#EF704F", "#F29071", "#949599", "#6193CE", "#207BBE"), guide = guide_legend (reverse=TRUE)) +
  labs(
    title = "MPs perceptions about LV and RU media", 
    x = "Perception", 
    y = "Percentage", 
    fill = "Answer"
  ) 

```
```{r}
 df %>%
select(info_soc_prob, info_import_pub, info_public, inf_other_mp, info_pol_weapon, info_imp_parties)%>%
 # select(`info_soc_prob`, `info_import_pub`)%>%
       sjPlot::plot_likert(title = "What MPs seek in the news media", axis.titles = "Information", catcount = 5,
  expand.grid = FALSE, show.n = TRUE,
  values = "show", show.prc.sign = TRUE, geom.colors = "RdBu",
  reverse.scale = TRUE) +
  scale_fill_manual(name = "Answers", labels = c("Never", "Seldom", "Now and then", "Often", "Very often"), values = c("#EF704F", "#F29071", "#949599", "#6193CE", "#207BBE"), guide = guide_legend (reverse=TRUE)) 
```

```


